export const FETCH_RESTAURANTS = 'FETCH_RESTAURANTS'
export const SET_RESTAURANTS = 'SET_RESTAURANTS'
export const FETCH_RESTAURANT = 'FETCH_RESTAURANT'
export const SET_OPENED_RESTAURANT = 'SET_OPENED_RESTAURANT'
